default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://127.0.0.1:6379/1" } %>
  channel_prefix: flag_manager

development:
  <<: *default

test:
  <<: *default
  channel_prefix: flag_manager_test

production:
  <<: *default
  channel_prefix: flag_manager_test
